// Phoenix rebuild note: this file was generated by the imported app, then
// wrapped so the public funnel can render without requiring local secrets.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const disabledError = {
  name: "SupabaseConfigMissing",
  message: "Supabase is not configured for this local rebuild.",
};

function createDisabledQuery() {
  const response = { data: [], error: disabledError };
  const singleResponse = { data: null, error: disabledError };
  const query = {
    select: () => query,
    eq: () => query,
    order: () => query,
    limit: async () => response,
    maybeSingle: async () => singleResponse,
    single: async () => singleResponse,
  };
  return query;
}

const disabledSupabaseClient = {
  functions: {
    invoke: async () => ({ data: null, error: disabledError }),
  },
  from: () => createDisabledQuery(),
} as unknown as ReturnType<typeof createClient<Database>>;

export const supabase = hasSupabaseConfig ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) : disabledSupabaseClient;

export const isSupabaseConfigured = hasSupabaseConfig;
